spring:
  rabbitmq:
    host: javaschoolrmqrv2dutokzu7as-vm0.southcentralus.cloudapp.azure.com
    port: 5672
    username: user
    password: JavaSchool.1234

rabbit:
  exchange: db-exchange
  routing-key: "#"
  queue: db-queue

server:
  port: 3000
management:
  server:
    port: 3001
    address: 127.0.0.1