server:
  port: 8080

config-rabbit:
  queue_shipping: db-queue
  exchange_shipping: db-exchange
  routing_key_shipping: "#"

spring:
  rabbitmq:
    host: javaschoolrmqrv2dutokzu7as-vm0.southcentralus.cloudapp.azure.com
    port: 5672
    username: user
    password: JavaSchool.1234

health:
  rabbit:
    enabled: false